### ISSUE TITLE
Inserts just a "1" instead of consecutive numbers

### ISSUE THREAD

**Issue by csu** [jbrooksuk/InsertNums#18]
When I select multiple empty lines and run Insert Nums with '', '1', and '1:1', it replaces all of the lines with just a single '1'.

**Comment by FichteFoll** [comment]
Is this always reproducable? Something in the console?

**Comment by csu** [comment]
I got no console output, but here's a screen recording: http://i.imgur.com/KM24OVj.gif

**Comment by FichteFoll** [comment]
Ah, that's nice (I probably would not have seen this otherwise). You need to reate multiple selections as InsertNums will insert a number for each selection. Since you only have one spanning multiple lines it would just replace that.

Press cmd+shift+l to split a multi-line selections into multiple selections before running InsertNums. Alternatively you could also use the `@` stop expression syntax if you need a fixed amount of numbers (which will insert the necessary amount of newlines).

**Comment by csu** [comment]
Ah, got it. Thank you!

**Comment by FichteFoll** [comment]
I should probably create a few gifs for this plugin, I can imagine it's rather hard to grasp with all the text.
